#!/usr/bin/env node
/**
 * Emit the cross-implementation test vectors.
 *
 * There are two implementations of this protocol — the TypeScript one in
 * `protocol/src` and the Swift one in `ios/Rowel/Protocol` — and a wire protocol
 * with two implementations is a wire protocol with two dialects unless something
 * forces them to agree. This is that something: fixed keys and fixed ephemerals
 * make the whole handshake deterministic, so the Swift tests can assert on exact
 * bytes rather than on "it seemed to work against a server I also wrote".
 *
 * Regenerate with `npm run vectors` and commit the result. A diff in the output
 * is a protocol change, and should be read as one.
 */

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  NoiseInitiator,
  NoiseResponder,
  TUNNEL_PROLOGUE,
  TUNNEL_VERSIONS,
  confirmationNumber,
  decodePairingLink,
  deviceIdFor,
  encodeFrame,
  encodePairingLink,
  keyFingerprint,
  normalizeShortCode,
  publicKeyOf,
  signPairOffer,
  signRegistration,
  signingPublicKeyOf,
} from '../lib/index.js'

/** Fixed key material. Every byte here is public by construction. */
const FIXTURES = {
  bridleStatic: '4a6f42b9c1d0e8f7a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9',
  appStatic: '1122334455667788990011223344556677889900112233445566778899001122',
  initiatorEphemeral: 'aabbccddeeff00112233445566778899aabbccddeeff00112233445566778899',
  responderEphemeral: '0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0',
  bridleSigning: '7766554433221100ffeeddccbbaa99887766554433221100ffeeddccbbaa9988',
}

/**
 * Build a raw key pair from a fixed private scalar.
 * @param {string} hex - 32 bytes of private key, hex encoded.
 * @returns {{privateKey: Buffer, publicKey: Buffer}} the pair.
 */
function pair(hex) {
  const privateKey = Buffer.from(hex, 'hex')
  return { privateKey, publicKey: publicKeyOf(privateKey) }
}

const bridle = pair(FIXTURES.bridleStatic)
const app = pair(FIXTURES.appStatic)
const initiatorEphemeral = pair(FIXTURES.initiatorEphemeral)
const responderEphemeral = pair(FIXTURES.responderEphemeral)
const signing = { privateKey: Buffer.from(FIXTURES.bridleSigning, 'hex'), publicKey: signingPublicKeyOf(Buffer.from(FIXTURES.bridleSigning, 'hex')) }

const helloPayload = Buffer.from(JSON.stringify({ versions: TUNNEL_VERSIONS, name: 'Test iPhone', client: 'rowel-vectors/1' }), 'utf8')
const replyPayload = Buffer.from(JSON.stringify({ ok: true, machine: 'Vector Mac', bridle: '0.1.0' }), 'utf8')

const initiator = new NoiseInitiator(app, bridle.publicKey, TUNNEL_PROLOGUE, initiatorEphemeral)
const responder = new NoiseResponder(bridle, TUNNEL_PROLOGUE, responderEphemeral)

const messageOne = initiator.writeMessage(helloPayload)
const read = responder.readMessage(messageOne)
const written = responder.writeMessage(replyPayload)
const established = initiator.readMessage(written.message)

// Both directions, several frames each, so a counter that advances wrongly on
// one side cannot hide behind a single-frame test.
const appToBridle = ['{"t":"req","id":"p1","method":"host.describe","payload":{}}', '{"t":"resume","since":0}', '{"t":"pong","nonce":"42"}']
  .map(text => established.channel.encrypt(Buffer.from(text, 'utf8')).toString('base64'))
const bridleToApp = ['{"t":"ready","version":1,"bridle":"0.1.0","machine":"Vector Mac","dshReachable":true,"seq":7}', '{"t":"ev","seq":8,"stream":"mux","frame":{"type":"session/subscribed","sessionId":"s1","lastSeq":3}}']
  .map(text => written.channel.encrypt(Buffer.from(text, 'utf8')).toString('base64'))

const bundle = {
  v: 1,
  relay: 'https://relay.rowel.app',
  direct: ['ws://192.168.1.20:61000'],
  device: deviceIdFor(signing.publicKey),
  key: bridle.publicKey.toString('base64url'),
  token: 'Uf9xQ2nKpL4mNvB7cZ0aRg',
  name: 'Vector Mac',
}

const nonce = 'ZmFrZS1ub25jZS1mb3ItdmVjdG9ycw'
const vectors = {
  note: 'Generated by protocol/scripts/emit-vectors.js. Do not edit by hand; run `npm run vectors`.',
  protocolName: 'Noise_IK_25519_ChaChaPoly_SHA256',
  prologue: TUNNEL_PROLOGUE.toString('base64'),
  keys: {
    bridleStaticPrivate: bridle.privateKey.toString('base64'),
    bridleStaticPublic: bridle.publicKey.toString('base64'),
    appStaticPrivate: app.privateKey.toString('base64'),
    appStaticPublic: app.publicKey.toString('base64'),
    initiatorEphemeralPrivate: initiatorEphemeral.privateKey.toString('base64'),
    responderEphemeralPrivate: responderEphemeral.privateKey.toString('base64'),
    bridleSigningPrivate: signing.privateKey.toString('base64'),
    bridleSigningPublic: signing.publicKey.toString('base64'),
  },
  handshake: {
    helloPayload: helloPayload.toString('base64'),
    messageOne: messageOne.toString('base64'),
    replyPayload: replyPayload.toString('base64'),
    messageTwo: written.message.toString('base64'),
    handshakeHash: established.channel.handshakeHash.toString('base64'),
    confirmationNumber: confirmationNumber(established.channel.handshakeHash),
  },
  transport: {
    appToBridlePlaintext: ['{"t":"req","id":"p1","method":"host.describe","payload":{}}', '{"t":"resume","since":0}', '{"t":"pong","nonce":"42"}'],
    appToBridle,
    bridleToAppPlaintext: ['{"t":"ready","version":1,"bridle":"0.1.0","machine":"Vector Mac","dshReachable":true,"seq":7}', '{"t":"ev","seq":8,"stream":"mux","frame":{"type":"session/subscribed","sessionId":"s1","lastSeq":3}}'],
    bridleToApp,
  },
  pairing: {
    bundle,
    link: encodePairingLink(bundle),
    deviceId: bundle.device,
    fingerprint: keyFingerprint(bridle.publicKey),
    shortCodeInputs: [
      { typed: 'ktpq3wrm', normalized: normalizeShortCode('ktpq3wrm') },
      { typed: 'KTPQ-3WRM', normalized: normalizeShortCode('KTPQ-3WRM') },
      { typed: ' ktpq 3wrm ', normalized: normalizeShortCode(' ktpq 3wrm ') },
    ],
  },
  // Signatures are base64url, and the signed body is spelled out here: the
  // domain separator is part of the message, and an implementation that signs
  // the bare nonce would interoperate right up until it did not.
  relayAuth: {
    nonce,
    registrationBody: `rowel-relay-registration/v1\n${nonce}`,
    registrationSignature: signRegistration(signing.privateKey, nonce),
    pairOfferCode: 'KTPQ-3WRM',
    pairOfferBody: 'rowel-pair-offer/v1\nKTPQ-3WRM',
    pairOfferSignature: signPairOffer(signing.privateKey, 'KTPQ-3WRM'),
  },
  frames: [
    ...[
      { t: 'call', id: 'c1', endpoint: 'session/list', args: { _request: {} } },
      { t: 'abort', id: 'c1' },
      { t: 'open', sid: 's1', endpoint: 'session/follow', args: { request: { address: { kind: 'session', sessionId: 'session-1' }, assistantStream: true, maxMessages: 25 } } },
      // One key: the value is the caller's own JSON, and key order is not part of it.
      { t: 'item', sid: 's1', value: { text: 'hi' } },
      { t: 'end', sid: 's1' },
      { t: 'cancel', sid: 's1' },
    ].map((frame) => ({ frame, encoded: encodeFrame(frame).toString('base64') })),
    // Both shapes of `wake`, because the withdrawal is the one an
    // implementation is most likely to get wrong: a `null` that JSON.stringify
    // keeps and a Swift optional that would silently drop the key are not the
    // same frame, and the difference is a machine that goes on ringing a phone
    // which asked to be left alone.
    { frame: { t: 'wake', token: 'a1b2c3' }, encoded: encodeFrame({ t: 'wake', token: 'a1b2c3' }).toString('base64') },
    { frame: { t: 'wake', token: null }, encoded: encodeFrame({ t: 'wake', token: null }).toString('base64') },
  ],
}

// Prove the round trip before writing: a vector file that does not describe a
// working handshake is worse than none.
if (read.payload.toString('utf8') !== helloPayload.toString('utf8')) throw new Error('responder did not recover the hello payload')
if (established.payload.toString('utf8') !== replyPayload.toString('utf8')) throw new Error('initiator did not recover the reply payload')
if (!read.remoteStatic.equals(app.publicKey)) throw new Error('responder authenticated the wrong initiator')
if (decodePairingLink(vectors.pairing.link).token !== bundle.token) throw new Error('pairing link does not round trip')

const here = dirname(fileURLToPath(import.meta.url))
const target = join(here, '..', '..', 'ios', 'RowelTests', 'Fixtures', 'protocol-vectors.json')
writeFileSync(target, `${JSON.stringify(vectors, null, 2)}\n`)
process.stdout.write(`wrote ${target}\n`)
