/// Byte-for-byte agreement with the TypeScript implementation.
///
/// There are two implementations of this protocol and no authority between them,
/// so "it worked against a server I also wrote" proves nothing. These vectors are
/// generated by `protocol/scripts/emit-vectors.js` with fixed keys and fixed
/// ephemerals, which makes the entire handshake deterministic — every assertion
/// here is on exact bytes produced by the other implementation.
///
/// A failure in this file is a protocol divergence, not a flaky test.

import XCTest
@testable import Rowel

final class ParityTests: XCTestCase {
    private var vectors: Vectors!

    override func setUpWithError() throws {
        vectors = try Vectors.load()
    }

    // MARK: - Names and constants

    func testProtocolNameMatches() {
        XCTAssertEqual(noiseProtocolName, vectors.string("protocolName"))
    }

    func testPrologueMatches() {
        XCTAssertEqual(tunnelPrologue, vectors.base64("prologue"))
    }

    // MARK: - Handshake

    /// Message one, produced by Swift with the vectors' ephemeral, must equal the
    /// bytes TypeScript produced. This covers the whole `e, es, s, ss` sequence:
    /// the hash chain, both DH operations, and two AEAD encryptions with the
    /// running hash as associated data.
    func testHandshakeMessageOneMatchesByte() throws {
        let initiator = try NoiseInitiator(
            staticKeys: try keyPair("appStaticPrivate"),
            remoteStatic: vectors.base64("keys", "bridleStaticPublic"),
            prologue: tunnelPrologue,
            ephemeral: try keyPair("initiatorEphemeralPrivate")
        )
        let message = try initiator.writeMessage(vectors.base64("handshake", "helloPayload"))
        XCTAssertEqual(message, vectors.base64("handshake", "messageOne"))
    }

    /// The hello payload the app states inside message one. The vectors carry the
    /// exact bytes the Bridle's parser was written against.
    func testHandshakeRequestEncodesIdentically() throws {
        let request = HandshakeRequest(name: "Test iPhone", client: "rowel-vectors/1", token: nil)
        XCTAssertEqual(try request.encoded(), vectors.base64("handshake", "helloPayload"))
    }

    /// A device that is already paired sends no token, and the key has to be
    /// absent rather than null: the Bridle treats `undefined` as "known device,
    /// no offer to redeem" and would otherwise try to redeem a null one.
    func testHandshakeRequestOmitsAbsentToken() throws {
        let without = try HandshakeRequest(name: "a", client: "b", token: nil).encoded()
        XCTAssertEqual(String(data: without, encoding: .utf8), #"{"versions":[2],"name":"a","client":"b"}"#)
        let with = try HandshakeRequest(name: "a", client: "b", token: "t").encoded()
        XCTAssertEqual(String(data: with, encoding: .utf8), #"{"versions":[2],"name":"a","client":"b","token":"t"}"#)
    }

    /// The prologue must carry no version.
    ///
    /// This is the property that lets a version mismatch be *answered* instead
    /// of failing inside the handshake: both ends mix the same prologue, so the
    /// responder can always decrypt message one and always reply.
    func testPrologueCarriesNoVersion() {
        let text = String(data: tunnelPrologue, encoding: .utf8)
        XCTAssertEqual(text, "rowel-tunnel")
        XCTAssertFalse(text?.contains("/v") ?? true, "a version in the prologue makes a mismatch unanswerable")
    }

    /// A refusal has to say which end is behind, or "update the older one"
    /// leaves the person guessing.
    func testRefusalNamesTheOlderEnd() throws {
        func reply(_ supported: [Int]) throws -> HandshakeReply {
            let json = #"{"ok":false,"reason":"version","supported":\#(supported)}"#
            return try JSONDecoder().decode(HandshakeReply.self, from: Data(json.utf8))
        }
        XCTAssertTrue(try reply([9]).weAreTheOldEnd, "the machine speaks newer, so this app is behind")
        XCTAssertFalse(try reply([0]).weAreTheOldEnd, "the machine speaks older, so it is behind")
        // No list at all: we cannot tell, and must not claim to.
        let bare = try JSONDecoder().decode(HandshakeReply.self, from: Data(#"{"ok":false,"reason":"version"}"#.utf8))
        XCTAssertFalse(bare.weAreTheOldEnd)
    }

    /// The other direction: Swift as responder must recover the initiator's
    /// identity and payload from bytes TypeScript wrote, and must produce the same
    /// message two.
    func testHandshakeRespondsIdentically() throws {
        let responder = NoiseResponder(
            staticKeys: try keyPair("bridleStaticPrivate"),
            prologue: tunnelPrologue,
            ephemeral: try keyPair("responderEphemeralPrivate")
        )
        let read = try responder.readMessage(vectors.base64("handshake", "messageOne"))
        XCTAssertEqual(read.remoteStatic, vectors.base64("keys", "appStaticPublic"))
        XCTAssertEqual(read.payload, vectors.base64("handshake", "helloPayload"))

        let written = try responder.writeMessage(vectors.base64("handshake", "replyPayload"))
        XCTAssertEqual(written.message, vectors.base64("handshake", "messageTwo"))
    }

    /// The channel binding value both ends derive. Everything about trust rests on
    /// this being the same number on both screens.
    func testHandshakeHashAndConfirmationNumber() throws {
        let (channel, payload) = try establish()
        XCTAssertEqual(payload, vectors.base64("handshake", "replyPayload"))
        XCTAssertEqual(channel.handshakeHash, vectors.base64("handshake", "handshakeHash"))
        XCTAssertEqual(
            Pairing.confirmationNumber(handshakeHash: channel.handshakeHash),
            vectors.string("handshake", "confirmationNumber")
        )
    }

    // MARK: - Transport

    /// Several frames in each direction. One frame would pass even if the nonce
    /// counter never advanced.
    func testTransportEncryptionMatches() throws {
        let (channel, _) = try establish()
        let plaintexts = vectors.strings("transport", "appToBridlePlaintext")
        let expected = vectors.strings("transport", "appToBridle")
        XCTAssertEqual(plaintexts.count, expected.count)
        for (text, cipher) in zip(plaintexts, expected) {
            let produced = try channel.encrypt(Data(text.utf8))
            XCTAssertEqual(produced.base64EncodedString(), cipher, "frame: \(text)")
        }
    }

    func testTransportDecryptionMatches() throws {
        let (channel, _) = try establish()
        let ciphertexts = vectors.strings("transport", "bridleToApp")
        let expected = vectors.strings("transport", "bridleToAppPlaintext")
        XCTAssertEqual(ciphertexts.count, expected.count)
        for (cipher, text) in zip(ciphertexts, expected) {
            guard let data = Data(base64Encoded: cipher) else { return XCTFail("bad vector") }
            let produced = try channel.decrypt(data)
            XCTAssertEqual(String(data: produced, encoding: .utf8), text)
        }
    }

    /// A tampered frame must not decrypt. This is the property the whole design
    /// leans on: the Relay forwards bytes and cannot alter them undetected.
    func testTamperedFrameIsRejected() throws {
        let (channel, _) = try establish()
        guard var data = Data(base64Encoded: vectors.strings("transport", "bridleToApp")[0]) else {
            return XCTFail("bad vector")
        }
        data[data.count - 1] ^= 0x01
        XCTAssertThrowsError(try channel.decrypt(data))
    }

    /// Frames arriving out of order must fail, because ChaCha20-Poly1305 nonces
    /// are counters and a stream that silently resynchronised would be forgeable.
    func testOutOfOrderFrameIsRejected() throws {
        let (channel, _) = try establish()
        let ciphertexts = vectors.strings("transport", "bridleToApp")
        guard let second = Data(base64Encoded: ciphertexts[1]) else { return XCTFail("bad vector") }
        XCTAssertThrowsError(try channel.decrypt(second))
    }

    // MARK: - Pairing

    func testPairingLinkDecodes() throws {
        let bundle = try Pairing.decodeLink(vectors.string("pairing", "link"))
        XCTAssertEqual(bundle.device, vectors.string("pairing", "bundle", "device"))
        XCTAssertEqual(bundle.key, vectors.string("pairing", "bundle", "key"))
        XCTAssertEqual(bundle.token, vectors.string("pairing", "bundle", "token"))
        XCTAssertEqual(bundle.name, vectors.string("pairing", "bundle", "name"))
        XCTAssertEqual(bundle.relay, vectors.string("pairing", "bundle", "relay"))
        XCTAssertEqual(bundle.direct, ["ws://192.168.1.20:61000"])
        XCTAssertEqual(bundle.staticKey, vectors.base64("keys", "bridleStaticPublic"))
    }

    /// Encoding must reproduce the exact link TypeScript emitted, which means the
    /// JSON has to serialise identically — key order and unescaped slashes both.
    func testPairingLinkEncodesIdentically() throws {
        let bundle = try Pairing.decodeLink(vectors.string("pairing", "link"))
        XCTAssertEqual(Pairing.encodeLink(bundle), vectors.string("pairing", "link"))
    }

    func testKeyFingerprintMatches() {
        XCTAssertEqual(
            Pairing.keyFingerprint(vectors.base64("keys", "bridleStaticPublic")),
            vectors.string("pairing", "fingerprint")
        )
    }

    func testShortCodeNormalisation() {
        for entry in vectors.array("pairing", "shortCodeInputs") {
            guard let typed = entry["typed"]?.stringValue,
                  let normalized = entry["normalized"]?.stringValue else {
                return XCTFail("bad vector")
            }
            XCTAssertEqual(Pairing.normalizeShortCode(typed), normalized, "input: \(typed)")
            XCTAssertTrue(Pairing.isCompleteShortCode(typed), "input: \(typed)")
        }
    }

    func testIncompleteShortCodesRejected() {
        XCTAssertFalse(Pairing.isCompleteShortCode("KTPQ"))
        XCTAssertFalse(Pairing.isCompleteShortCode("KTPQ-3WRMX"))
        // The alphabet excludes vowels and look-alikes, so these cannot be codes.
        XCTAssertFalse(Pairing.isCompleteShortCode("KTPQ-3WR0"))
        XCTAssertFalse(Pairing.isCompleteShortCode("KTPQ-3WRA"))
    }

    func testDamagedLinksRejected() {
        XCTAssertThrowsError(try Pairing.decodeLink("https://rowel.app/pair#abc"))
        XCTAssertThrowsError(try Pairing.decodeLink("rowel://pair"))
        XCTAssertThrowsError(try Pairing.decodeLink("rowel://pair#not-base64!!"))
    }

    // MARK: - Frames

    /// Frame encoding must match byte for byte, or the Bridle's JSON parser sees
    /// something subtly different from what it was tested against.
    func testFrameEncodingMatches() throws {
        for entry in vectors.array("frames") {
            guard let frame = entry["frame"], let expected = entry["encoded"]?.stringValue else {
                return XCTFail("bad vector")
            }
            let encoded: Data
            switch frame["t"]?.stringValue {
            case "call":
                encoded = try CallFrame(
                    id: frame["id"]?.stringValue ?? "",
                    endpoint: frame["endpoint"]?.stringValue ?? "",
                    args: frame["args"] ?? .emptyObject
                ).encoded()
            case "abort":
                encoded = try AbortFrame(id: frame["id"]?.stringValue ?? "").encoded()
            case "open":
                encoded = try OpenFrame(
                    sid: frame["sid"]?.stringValue ?? "",
                    endpoint: frame["endpoint"]?.stringValue ?? "",
                    args: frame["args"] ?? .emptyObject
                ).encoded()
            case "item":
                encoded = try UplinkItemFrame(sid: frame["sid"]?.stringValue ?? "", value: frame["value"] ?? .null).encoded()
            case "end":
                encoded = try UplinkEndFrame(sid: frame["sid"]?.stringValue ?? "").encoded()
            case "cancel":
                encoded = try CancelFrame(sid: frame["sid"]?.stringValue ?? "").encoded()
            case "wake":
                encoded = try WakeFrame(token: frame["token"]?.stringValue).encoded()
            default:
                return XCTFail("unhandled frame kind in vectors")
            }
            XCTAssertEqual(encoded.base64EncodedString(), expected)
        }
    }

    // MARK: - Helpers

    private func establish() throws -> (SecureChannel, Data) {
        let initiator = try NoiseInitiator(
            staticKeys: try keyPair("appStaticPrivate"),
            remoteStatic: vectors.base64("keys", "bridleStaticPublic"),
            prologue: tunnelPrologue,
            ephemeral: try keyPair("initiatorEphemeralPrivate")
        )
        _ = try initiator.writeMessage(vectors.base64("handshake", "helloPayload"))
        return try initiator.readMessage(vectors.base64("handshake", "messageTwo"))
    }

    private func keyPair(_ name: String) throws -> StaticKeyPair {
        try StaticKeyPair(privateKey: vectors.base64("keys", name))
    }
}

// MARK: - Fixture access

/// The vector file, with accessors that fail the test rather than crash it.
struct Vectors {
    let root: JSONValue

    static func load() throws -> Vectors {
        guard let url = Bundle(for: ParityTests.self).url(forResource: "protocol-vectors", withExtension: "json") else {
            throw VectorError.missing
        }
        return Vectors(root: try JSONValue(data: try Data(contentsOf: url)))
    }

    func node(_ path: [String]) -> JSONValue? {
        var value: JSONValue? = root
        for key in path { value = value?[key] }
        return value
    }

    func string(_ path: String...) -> String {
        node(path)?.stringValue ?? ""
    }

    func strings(_ path: String...) -> [String] {
        (node(path)?.arrayValue ?? []).compactMap { $0.stringValue }
    }

    func array(_ path: String...) -> [JSONValue] {
        node(path)?.arrayValue ?? []
    }

    /// A standard-base64 value from the fixtures, as bytes.
    func base64(_ path: String...) -> Data {
        Data(base64Encoded: node(path)?.stringValue ?? "") ?? Data()
    }
}

enum VectorError: Error {
    case missing
}
